region                     = "eu-west-1"
vpc_cidr                   = "10.0.0.0/16"
public_subnets             = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets            = ["10.0.3.0/24", "10.0.4.0/24"]
azs                        = ["eu-west-1a", "eu-west-1b"]
instance_type              = "t3.micro"
packer_ami_name_pattern    = ""
packer_ami_owner           = ""
ami_id                     = ""
key_name                  = "my-key-pair"